# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f62e312c1fdb9c64dd80427ace6b084dbf3d2f2422c6485fb51fe0dd9ad05c4d3cce11897ac0f79926f349f0e0342d66f49cbb3caf66fe6e15fb346aafde14d4

test:
  secret_key_base: 5f850a0c73c344bc65380e2a15012b62db3177d214c6476d91fa4690f2b7beceddfa62065f9b3efc16fac7914b73eb3fa8c9fe4cbb18042ac272c20fd4e8bd2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
